### ISSUE TITLE
Add bundled version

### ISSUE THREAD

**Issue by arkon** [superguigui/simple-color-picker#13]
It'd be nice if people could use it just be adding a `<script>` to their page instead of relying on common.js.

**Comment by superguigui** [comment]
Again this is long overdue but I've added how to do this in the README :
You can make use of the new bundles with UNPKG cdn to load the files directly without a package manager.
```html
<link rel="stylesheet" href="https://unpkg.com/simple-color-picker/dist/simple-color-picker.css"/>
<script src="https://unpkg.com/simple-color-picker/dist/simple-color-picker.umd.js"/>
```
