### ISSUE TITLE
Using units other than pixels causes only parts of the color picker to be clickable

### ISSUE THREAD

**Issue by bjdixon** [superguigui/simple-color-picker#17]
Moving the color and hue selectors uses a clamp function that ensures the coordinates are bounded within the dimensions of the color selector elements coordinates. Unfortunately it is supplied a value that expects pixels but when using a unit of a different type (vw, vh, %) it takes the unit value as the pixel value. 

For example setting width to 50% sets the saturationWidth to 50px. This means that on a viewport with 500px width the color picker will show as being 250px wide but only the first 50px of that width is clickable. The same bug is present for height and the hue selector height.

**Comment by arkon** [comment]
Fixed via #18. Thanks @bjdixon !
