### ISSUE TITLE
Included .css doesn't match example

### ISSUE THREAD

**Issue by k-funk** [superguigui/simple-color-picker#26]
The sample at http://superguigui.github.io/simple-color-picker/ uses
```
.Scp-saturation {
  ...
  width: calc(100% - 25px);
}
```
which isn't in the included .css.

The .js also overrides the .Scp-saturation element, so it's not an easy fix. What I get is:
<img width="389" alt="9672efe0-e256-11e6-9a90-5b38887917fc" src="https://user-images.githubusercontent.com/1933021/31474868-4f1d29c0-aeb2-11e7-8301-9013aa3f371c.png">

**Comment by cernym43** [comment]
+1

**Comment by superguigui** [comment]
Hey guys.

Indeed I have to update the demo as the width is now fully set from the script to avoid other issues (see https://github.com/superguigui/simple-color-picker/pull/21).

How do you instantiate your color picker ?

**Comment by k-funk** [comment]
This is probably more info than you want, but here's my full use case, in case I'm doing something that you find unusual:

.ejs template
```
<input type="text" class="form-control" value="<%= locals.color %>" placeholder="#0000FF">
```
.js Backbone View
```
const inputField = this.$(e.target);
const el = inputField.parent().siblings('.scp-container').get(0);
const colorPicker = new ColorPicker({
  el,
  color: inputField.val(),
  background: '#FFFFFF',
  height: '200',
  width: '250',
});
colorPicker.onChange((color) => {
  this.model.set(this.modelProperty, color.toUpperCase(), { silent: true });
  inputField.val(color.toUpperCase());
  this.setColorPreview();
});
```
.scss
```
.scp-container {
  position: relative;
  .Scp {
    background-color: #FFF;
    position: absolute;
    z-index: 10;
    ...
  }
}
```

**Comment by superguigui** [comment]
This is long overdue (real sorry about that), but latest JS and css version should fix styling problems.
