### ISSUE TITLE
prefix dependency broken?

### ISSUE THREAD

**Issue by lerayj** [superguigui/simple-color-picker#9]
One of your dependency `dom-transform` have `prefix` as depencency which seems to be broken. 
`prefix` looking for the file `browser.js`, which is not downloaded on npm use, but it's present on the GitHub repo:  [prefix repo](https://github.com/jkroso/prefix#readme )

Am I right?

**Comment by superguigui** [comment]
Hi Julien !
You are perfectly right the prefix module seems a bit broken on NPM.
Are you experiencing a problem in particular ?
The color picker seems to be working fine on my end.

**Comment by lerayj** [comment]
Hi!
Actually your package does not work for me due to this dependency issue.
My project fail and ask me to npm install browser.js (which is bullshit, browser.js is just a file not a package).

I've to manually add missing file on the dependency to make it work... 
I don't want to do that so I found an other colorPicker with no dependency.

Just wanted to tell you the issue ;)

**Comment by arkon** [comment]
I made [a PR to prefix](https://github.com/jkroso/prefix/pull/4) that _should_ fix it.
